// Auto-generated by scripts/render_backgrounds.py -- do not edit by hand.
#pragma once

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

LV_IMG_DECLARE(bg_main);
LV_IMG_DECLARE(bg_alarm);
LV_IMG_DECLARE(bg_brightness);
LV_IMG_DECLARE(bg_effects);
LV_IMG_DECLARE(bg_presets);
LV_IMG_DECLARE(bg_settings);
LV_IMG_DECLARE(bg_mic);
LV_IMG_DECLARE(bg_info);

#ifdef __cplusplus
}
#endif
