#!/usr/bin/env python3
"""Generate a baked HSV colour wheel as an LVGL RGB565 (no alpha) C asset.

Output: main/assets/color_wheel.c with symbol `color_wheel` (lv_img_dsc_t).

Wheel geometry:
  - Canvas 320x320 RGB565 little-endian (LV_COLOR_DEPTH=16, LV_COLOR_16_SWAP=0)
  - Outer radius = 156, inner cut = 0 (full disc)
  - Hue from atan2 in [0, 1), saturation = r / R, value = 1.0
  - Outside the disc: dark colour matching bg_colorpicker rim so the wheel
    blends into the screen without an alpha channel (saves 33% RAM).

Touch handler converts (x, y) on the 320x320 wheel to HSV → RGB.

Run from repo root:
    .venv/bin/python scripts/render_color_wheel.py
"""

from __future__ import annotations

import colorsys
import math
import os
from pathlib import Path
from PIL import Image

REPO_ROOT = Path(__file__).resolve().parents[1]
OUT_PATH = REPO_ROOT / "main" / "assets" / "color_wheel.c"

SIZE = 200
RADIUS = (SIZE // 2) - 4    # leave a few px so the disc edge does not clip
BG_RIM = (12, 14, 22)       # matches bg_colorpicker rim colour


def render_wheel() -> Image.Image:
    img = Image.new("RGB", (SIZE, SIZE), BG_RIM)
    px = img.load()
    cx = cy = SIZE // 2
    for y in range(SIZE):
        dy = y - cy
        for x in range(SIZE):
            dx = x - cx
            d = math.hypot(dx, dy)
            if d <= RADIUS:
                # hue 0 at +x axis, going CCW like the colorpicker icon
                hue = (math.atan2(dy, dx) / (2 * math.pi)) % 1.0
                sat = min(1.0, d / RADIUS)
                r, g, b = colorsys.hsv_to_rgb(hue, sat, 1.0)
                px[x, y] = (int(r * 255), int(g * 255), int(b * 255))
    return img


def to_rgb565_le(img: Image.Image) -> bytes:
    out = bytearray(SIZE * SIZE * 2)
    p = img.load()
    for y in range(SIZE):
        for x in range(SIZE):
            r, g, b = p[x, y]
            v = ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)
            i = (y * SIZE + x) * 2
            out[i] = v & 0xFF
            out[i + 1] = (v >> 8) & 0xFF
    return bytes(out)


def emit_c(data: bytes) -> str:
    rows = []
    chunk = []
    for i, b in enumerate(data):
        chunk.append(f"0x{b:02x}")
        if (i + 1) % 16 == 0:
            rows.append("    " + ",".join(chunk) + ",")
            chunk = []
    if chunk:
        rows.append("    " + ",".join(chunk) + ",")
    body = "\n".join(rows)
    return (
        "// Auto-generated by scripts/render_color_wheel.py -- do not edit by hand.\n"
        "#include \"lvgl.h\"\n\n"
        "#if LV_COLOR_DEPTH != 16 || LV_COLOR_16_SWAP != 0\n"
        "#error \"color_wheel.c assumes LV_COLOR_DEPTH=16, LV_COLOR_16_SWAP=0\"\n"
        "#endif\n\n"
        "static const LV_ATTRIBUTE_LARGE_CONST uint8_t color_wheel_map[] = {\n"
        f"{body}\n"
        "};\n\n"
        "const lv_img_dsc_t color_wheel = {\n"
        "    .header.cf = LV_IMG_CF_TRUE_COLOR,\n"
        "    .header.always_zero = 0,\n"
        "    .header.reserved = 0,\n"
        f"    .header.w = {SIZE},\n"
        f"    .header.h = {SIZE},\n"
        f"    .data_size = {len(data)},\n"
        "    .data = color_wheel_map,\n"
        "};\n"
    )


def main() -> None:
    img = render_wheel()
    img.save(OUT_PATH.with_suffix(".png"), "PNG")
    data = to_rgb565_le(img)
    OUT_PATH.write_text(emit_c(data))
    print(f"wrote {OUT_PATH.relative_to(REPO_ROOT)} ({len(data)/1024:.1f} KB)")


if __name__ == "__main__":
    main()
